---
- name: Nginx configuration
  hosts: appserver

  roles:
    - role: jdauphant.nginx

      nginx_user: "www-data"
      nginx_events_params:
        - worker_connections 1024
        - use epoll
        - accept_mutex off
        - multi_accept on
      nginx_worker_processes: auto
      nginx_worker_rlimit_nofile: 60000
      nginx_http_params:
        - sendfile on
        - sendfile_max_chunk 512k
        - send_timeout 10
        - tcp_nopush on
        - tcp_nodelay on
        - keepalive_timeout 15
        - types_hash_max_size 2048
        - open_file_cache max=1000 inactive=20s
        - open_file_cache_valid 30s
        - open_file_cache_min_uses 5
        - open_file_cache_errors off
        - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
        - ssl_prefer_server_ciphers on
        - client_body_buffer_size 10K
        - client_header_buffer_size 8k
        - client_max_body_size 75m
        - large_client_header_buffers 4 8k
        - client_body_timeout 12
        - client_header_timeout 12
        - proxy_cache_path /cache levels=1:2 keys_zone=odoo_cache:10m max_size=768m inactive=60m use_temp_path=off

      nginx_configs:
        upstream:
          - upstream odoo { server 127.0.0.1:8069; }
          - upstream odoochat { server 127.0.0.1:8072; }

        gzip:
          - gzip on
          - gzip_disable "msie6"
          - gzip_vary on
          - gzip_proxied any
          - gzip_comp_level 6
          - gzip_buffers 16 8k
          - gzip_http_version 1.1
          - gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript
          - gzip_min_length 10240
 
        proxy:
          - proxy_read_timeout 720s
          - proxy_connect_timeout 720s
          - proxy_send_timeout 720s
          - proxy_set_header X-Forwarded-Host $host
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
          - proxy_set_header X-Forwarded-Proto $scheme
          - proxy_set_header X-Real-IP $remote_addr


      nginx_sites:
        odoo:
          - listen 80
          - server_name {{ nginx_odoo_domain }}
          - access_log /var/log/nginx/odoo.access.log
          - error_log /var/log/nginx/odoo.error.log
          - |
            location / {
              proxy_buffers 8 24k;
              proxy_buffer_size 2k;
              proxy_redirect off;
              proxy_cache odoo_cache;
              proxy_cache_revalidate on;
              proxy_cache_min_uses 1;
              proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
              proxy_cache_lock on;
              proxy_pass http://odoo;
            }
          - |
            location /longpolling {
              proxy_buffers 8 24k;
              proxy_buffer_size 2k;
              proxy_pass http://odoochat;
            }
  pre_tasks:
    - name: Load Nginx Odoo Variables
      include_vars: ../variables.yml

    - name: Add HugePages group
      group:
        gid: 9999
        name: hugepages
        state: present

  post_tasks:
    - name: Joining WWW user to HugePages group
      user: name=www-data groups=hugepages append=yes

    - name: Create pam_limits and sysctl files
      file:
        path: "{{ item.filename }}"
        state: touch
        mode: 0644
      with_items:
        - { filename: "/etc/sysctl.d/30-nginx-shm.conf" }
        - { filename: "/etc/sysctl.d/31-network-tcp-tuning.conf" }
        - { filename: "/etc/security/limits.d/99-nginx.conf" }

    - name: /etc/security/limits.conf configuration
      pam_limits:
        domain: "{{ item.domain }}"
        limit_type: "{{ item.limit_type }}"
        limit_item: "{{ item.limit_item }}"
        value: "{{ item.value }}"
        dest: /etc/security/limits.d/99-nginx.conf
      with_items:
        - { domain: "@hugepages", limit_type: "soft", limit_item: "stack",   value: "unlimited" }
        - { domain: "@hugepages", limit_type: "hard", limit_item: "stack",   value: "unlimited" }
        - { domain: "@hugepages", limit_type: "soft", limit_item: "memlock", value: "unlimited" }
        - { domain: "@hugepages", limit_type: "hard", limit_item: "memlock", value: "unlimited" }
        - { domain: "www-data",   limit_type: "soft", limit_item: "nofile",  value: "65535" }
        - { domain: "www-data",   limit_type: "hard", limit_item: "nofile",  value: "65535" }

    - name: Creating cache directory for static files
      file:
        path: "{{ nginx_cache_dir }}"
        state: directory
        mode: 0755
        owner: "www-data"
        group: "www-data"
    
    - name: Adding cache mount point
      mount:
        name: "{{ nginx_cache_dir }}"
        src: tmpfs
        fstype: tmpfs
        opts: "rw,nodev,noexec,noatime,size=1048576k,mode=1777"
        state: present

    - name: Mounting nginx cache
      mount:
        name: "{{ nginx_cache_dir }}"
        src: tmpfs
        fstype: tmpfs
        opts: "rw,nodev,noexec,noatime,size=1048576k,mode=1777"
        state: mounted

    - name: Sysctl tuning for Nginx
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/30-nginx-shm.conf
        state: present
        reload: yes
      with_items:
        - { name: "vm.overcommit_memory", value: "2" }
        - { name: "vm.nr_hugepages", value: "148" }
        - { name: "vm.hugetlb_shm_group", value: "9999" }
        - { name: "vm.hugepages_treat_as_movable", value: "0" }
        - { name: "vm.nr_overcommit_hugepages", value: "64" }
        - { name: "fs.file-max", value: "81920" }

    - name: Sysctl tuning for TCP/IP Stack
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/31-network-tcp-tuning.conf
        state: present
        reload: yes
      with_items:
        - { name: "net.ipv4.ip_local_port_range", value: "1024 65535" }
        - { name: "net.ipv4.tcp_tw_recycle", value: "1" }
        - { name: "net.ipv4.tcp_tw_reuse", value: "1" }
        - { name: "net.ipv4.tcp_max_tw_buckets", value: "1440000" }
        - { name: "net.ipv4.tcp_fin_timeout", value: "7" }
        - { name: "net.ipv4.tcp_slow_start_after_idle", value: "0" }
        - { name: "net.ipv4.tcp_window_scaling", value: "1" }
        - { name: "net.ipv4.tcp_max_syn_backlog", value: "3240000" }
        - { name: "net.core.rmem_max", value: "16777216" }
        - { name: "net.core.wmem_max", value: "16777216" }
        - { name: "net.core.somaxconn", value: "65535" }
        - { name: "net.core.netdev_max_backlog", value: "2500" }
        - { name: "net.ipv4.tcp_rmem", value: "4096 87380 16777216" }
        - { name: "net.ipv4.tcp_wmem", value: "4096 65536 16777216" }
        - { name: "net.ipv4.tcp_syn_retries", value: "1" }
        - { name: "net.ipv4.tcp_synack_retries", value: "1" }
        - { name: "net.ipv4.tcp_keepalive_time", value: "15" }
        - { name: "net.ipv4.tcp_keepalive_intvl", value: "1" }
        - { name: "net.ipv4.tcp_keepalive_probes", value: "2" }
        - { name: "kernel.sched_migration_cost_ns", value: "5000000" }
        - { name: "kernel.sched_autogroup_enabled", value: "0" }

    - name: Restarting Nginx
      service:
        name: nginx
        state: restarted

